---
title: "Inframe Simulation Using Table Operations"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: show
    collapse: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE)
```

# Load
```{r load}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(simaerep))
```

# Performance (Time)

```{r}
df_visit <- sim_test_data_study(
  n_pat = 1000, # number of patients in study
  n_sites = 100, # number of sites in study
  frac_site_with_ur = 0.05, # fraction of sites under-reporting
  ur_rate = 0.4, # rate of under-reporting
  ae_per_visit_mean = 0.5 # mean AE per patient visit
)

df_visit$study_id <- "A"

# original settings visit_med75 always in memory, no over-reporting
system.time({simaerep(df_visit, inframe = FALSE, visit_med75 = TRUE, under_only = TRUE, progress = FALSE)})

# inframe with and without visit_med75
system.time({simaerep(df_visit, inframe = TRUE, visit_med75 = FALSE, under_only = TRUE)})
system.time({simaerep(df_visit, inframe = TRUE, visit_med75 = TRUE, under_only = TRUE)})

# original settings visit_med75 in memory, with over-reporting
system.time({simaerep(df_visit, inframe = FALSE, visit_med75 = TRUE, under_only = FALSE, progress = FALSE)})

# inframe with and without visit_med75 with over-reporting
system.time({simaerep(df_visit, inframe = TRUE, visit_med75 = FALSE, under_only = FALSE)})
system.time({simaerep(df_visit, inframe = TRUE, visit_med75 = TRUE, under_only = FALSE)})

```

# DB

```{r}
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = ":memory:")
df_r <- tibble(rep = seq(1, 1000))

dplyr::copy_to(con, df_visit, "visit")
dplyr::copy_to(con, df_r, "r")

tbl_visit <- tbl(con, "visit")
tbl_r <- tbl(con, "r")

system.time(simaerep(tbl_visit, r = tbl_r, check = TRUE))
system.time(simaerep(tbl_visit, r = tbl_r, check = FALSE))

```

# Performance (Statistical)

```{r}
suppressPackageStartupMessages(library(furrr))
suppressPackageStartupMessages(library(future))

plan(multisession, workers = 6)
```


## Load Portfolio

```{r}
df_config <- readr::read_csv("ae_conf_20240220.csv")
df_ae_rates <- readr::read_csv("ae_rates_20240220.csv")

df_portf_flex <- sim_test_data_portfolio(df_config, df_ae_rates = df_ae_rates, parallel = TRUE, progress = TRUE)
```

## Functions


```{r}
perf <- function(df_visit, study_id, site_number, ur_rate) {
  df_vs_study <- df_visit %>%
    sim_ur(study_id, site_number, ur_rate)
  
  prob_low_prob_ur_visit_med75 <- df_vs_study %>%
    simaerep(under_only = TRUE, progress = FALSE) %>%
    .$df_eval %>%
    filter(.data$site_number == .env$site_number) %>%
    pull(prob_low_prob_ur)
  
  prob_low_prob_ur_inframe <- df_vs_study %>%
    simaerep_inframe(under_only = TRUE) %>%
    filter(.data$site_number == .env$site_number) %>%
    pull(prob_low_prob_ur)
  
  prob_low_prob_ur_inframe_visit_med75 <- df_vs_study %>%
    simaerep_inframe(under_only = TRUE, method_visit_med75 = "med75_adj") %>%
    filter(.data$site_number == .env$site_number) %>%
    pull(prob_low_prob_ur)

  tibble(
    visit_med75 = prob_low_prob_ur_visit_med75,
    inframe = prob_low_prob_ur_inframe,
    inframe_visit_med75 = prob_low_prob_ur_inframe_visit_med75
  )
}

#perf(df_portf_flex, study_id = "0010", site_number = "15148", ur_rate = 1)
#perf(df_portf_flex, study_id = "0001", site_number = "4746", ur_rate = 0.75)
perf(df_portf_flex, study_id = "0010", site_number = "15148", ur_rate = 1)

```


## Grid

```{r}
df_grid <- df_portf_flex %>%
  distinct(study_id, site_number) %>%
  # to reduce calculation time we only take every xth study
  filter(dense_rank(study_id)%%50 == 0) %>%
  mutate(ur_rate = list(c(0, 0.1, 0.25, 0.5, 0.75, 1))) %>%
  unnest(ur_rate)

df_grid
```

## Apply

### inframe

```{r eval = FALSE}
with_progress_cnd(
  df_perf <- df_grid %>%
    mutate(
      perf = purrr_bar(
        list(study_id, site_number, ur_rate),
        .purrr = furrr::future_pmap,
        .f = function(x, y, z) list(perf(df_portf_flex, x, y, z)),
        .purrr_args = list(.options = furrr_options(seed = TRUE)),
        .steps = nrow(.)
      )
    )
)

df_perf %>%
  unnest(perf) %>%
  unnest(perf) %>%
  readr::write_csv("inframe.csv")
```

```{r}
df_perf <- readr::read_csv("inframe.csv")
```

# Evaluation

```{r}
df_perf %>%
  pivot_longer(c(visit_med75, inframe, inframe_visit_med75)) %>%
  summarise(
    n_ur = sum(value >= 0.95),
    n_sites = n_distinct(site_number),
    mean_ur_rate = mean(value),
    .by = c(ur_rate, name)
  )
```

