# satisfy lintr
# lintr falsely flags possibly_ecdf as unused variable
if (getRversion() >= "2.15.1") {
  utils::globalVariables(c("possibly_ecdf"))
}

#' @title evaluate sites
#' @description evaluate site simulations by assigning a probability to each
#'   scoring values using the score distributions of the study simulations. Then
#'   calculate the P/fp ratio for each site.
#' @param df_sim_sites dataframe generated by sim_sites()
#' @param r_sim_sites integer, simulation repeats for prob_lower for site
#'   simulation, Default: 1000
#' @return dataframe
#' @details zero probabilities are being replaced by the site minimum for
#'   ecd_pval / 10 and by 1/r_sim_sites / 10
#' @examples
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.4, ur_rate = 0.6)
#'
#' df_visit$study_roche <- "A"
#' df_site <- site_aggr(df_visit)
#'
#' df_sim_sites <- sim_sites(df_site, df_visit, r = 100)
#'
#' df_eval <- eval_sites(df_sim_sites, r_sim_sites = 100)
#' df_eval
#' @rdname eval_sites
#' @export
eval_sites <- function(df_sim_sites,
                       r_sim_sites = 1000) {


  df_out <- df_sim_sites

  # P/FP ratio ------------------------------------------------------------------

  if ("pval" %in% names(df_out)) {

    if (anyNA(df_out$pval)) {
      warning("pval column contains NA")
    }

    df_out <- df_out %>%
      group_by(.data$study_roche) %>%
      arrange(.data$study_roche, .data$pval) %>%
      mutate(
        n_site = n(),
        min_pval = min(.data$pval[.data$pval > 0]),
        # we need to use ties.method max because there can be more than one site with a
        # specific p value
        pval_n_detected = rank(.data$pval, ties.method = "max", na.last = "keep"),
        pval_fp = .data$pval * .data$n_site,
        pval_fp = ifelse(.data$pval_fp == 0, .data$min_pval / 10, .data$pval_fp),
        pval_p_vs_fp_ratio = .data$pval_n_detected / .data$pval_fp,
        pval_p_vs_fp_ratio = ifelse(is.na(.data$pval_p_vs_fp_ratio) & ! is.na(.data$pval),
                                    0, .data$pval_p_vs_fp_ratio),
        # it is possible to get ratios lower than one if p < expected fp
        # this can happen by chance and is meaningless
        pval_p_vs_fp_ratio = ifelse(pval_p_vs_fp_ratio < 1, 1, pval_p_vs_fp_ratio),
        pval_prob_ur = 1 - 1 / .data$pval_p_vs_fp_ratio
      ) %>%
      select(- .data$min_pval)
  }

  if ("prob_low" %in% names(df_out)) {

    if (anyNA(df_out$pval)) {
      warning("prob_lower column contains NA")
    }

    df_out <- df_out %>%
      group_by(.data$study_roche) %>%
      arrange(.data$study_roche, .data$prob_low) %>%
      mutate(
        n_site = n(),
        # we need to use ties.method max because there can be more than one site with a
        # specific prob_low value
        prob_low_n_detected = rank(.data$prob_low, ties.method = "max", na.last = "keep"),
        prob_low_fp = .data$prob_low * .data$n_site,
        prob_low_fp = ifelse(.data$prob_low_fp == 0, 1 / r_sim_sites / 10, .data$prob_low_fp),
        prob_low_p_vs_fp_ratio = .data$prob_low_n_detected / .data$prob_low_fp,
        prob_low_p_vs_fp_ratio = ifelse(is.na(.data$prob_low_p_vs_fp_ratio) & ! is.na(.data$prob_low),
                                        0, .data$prob_low_p_vs_fp_ratio),
        # it is possible to get ratios lower than one if p < expected fp
        # this can happen by chance and is meaningless
        prob_low_p_vs_fp_ratio = ifelse(prob_low_p_vs_fp_ratio < 1, 1, prob_low_p_vs_fp_ratio),
        prob_low_prob_ur = 1 - 1 / .data$prob_low_p_vs_fp_ratio
      )
  }

  return(ungroup(df_out))
}

#' @title get emprical cumulative distribution values, used by eval_sites()
#' @description no longer used.
#'   we fit an ecd function to the simulated studies and get ecd
#'   values for the site statistics.
#' @param df_sim_studies dataframe, generated by sim_studies()
#' @param df_sim_sites dataframem, generated by sim_sites()
#' @param val_str c("prob_low","pval")
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.4, ur_rate = 0.3)
#'
#' df_visit$study_roche <- "A"
#' df_site <- site_aggr(df_visit)
#'
#' df_sim_sites <- sim_sites(df_site, df_visit, r = 100)
#'
#' df_sim_studies <- sim_studies(
#'   df_site = df_site,
#'   df_visit = df_visit,
#'   r = 3,
#'   parallel = FALSE,
#'   poisson_test = TRUE,
#'   prob_lower = TRUE
#' )
#'
#' get_ecd_values(df_sim_studies, df_sim_sites, "prob_low")
#' get_ecd_values(df_sim_studies, df_sim_sites, "pval")
#' @rdname get_ecd_values
#' @noRd
get_ecd_values <- function(df_sim_studies, df_sim_sites, val_str) {

  possibly_ecdf <- possibly(ecdf, otherwise = NA)

  apply_ecdf <- function(.f, x) {
      if (suppressWarnings(is.na(.f))) {
        warning("NA Values in Stats")
        return(NA)
      } else {
        return(.f(x))
      }
  }

  df_ecd <- df_sim_studies %>%
    rename(val = !!as.symbol(val_str)) %>%
    select(.data$study_roche, .data$val) %>%
    nest(data = c(.data$val)) %>%
    mutate(.ecdf = map(.data$data, ~ possibly_ecdf(.$val))) %>%
    select(- .data$data)

  df_out <- df_sim_sites %>%
    rename(val = !!as.symbol(val_str)) %>%
    left_join(df_ecd, "study_roche") %>%
    mutate(ecd_val = map2_dbl(.data$`.ecdf`, .data$val, apply_ecdf)) %>%
    rename(
      !!as.symbol(val_str) := .data$val,
      !!as.symbol(paste0(val_str, "_ecd")) := .data$ecd_val
    ) %>%
    select(- .data$`.ecdf`)

  return(ungroup(df_out))
}



#' @title create patient pool for sampling for simulations
#' @description filter all visits greater than max_visit_med75_study
#' returns dataframe with one column for studies and one column with nested
#' patient data.
#' @param df_visit dataframe
#' @param df_site dataframe
#' @return dataframe with nested pat_pool column
#' @details " "
#' @examples
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.4, ur_rate = 0.6)
#'
#' df_visit$study_roche <- "A"
#' df_site <- site_aggr(df_visit)
#'
#' df_pat_pool <- pat_pool(df_visit, df_site)
#' df_pat_pool
#' @rdname pat_pool
#' @export
pat_pool <- function(df_visit, df_site) {
  df_site <- df_site %>%
    group_by(.data$study_roche) %>%
    mutate(max_visit_med75_study = max(.data$visit_med75))

  df_visit %>%
    left_join(df_site, by = c("study_roche", "site_number")) %>%
    filter(.data$visit <= .data$max_visit_med75_study) %>%
    select(.data$study_roche,
           .data$patnum,
           .data$visit,
           .data$n_ae) %>%
    nest(pat_pool = c(.data$patnum, .data$visit, .data$n_ae))
}




#' @title calculate probability for drawing a site sample with lower mean aes
#'   from total study pool for vector with site AEs vs vector with study AEs
#' @description sets pvalue=1 if mean AE site is greater than mean AE study
#' @param site_ae vector with AE numbers
#' @param study_ae vector with AE numbers
#' @param r integer, denotes number of simulations, default = 1000
#' @param parallel logical, toggles parallel processing on and of, default = F
#' @return pval
#' @details " "
#' @examples
#' prob_lower_site_ae_vs_study_ae(
#'   site_ae = c(5, 3, 3, 2, 1, 6),
#'   study_ae = c(9, 8, 7, 9, 6, 7, 8),
#'   parallel = FALSE
#' )
#' @seealso \code{\link[purrr]{safely}}
#' @rdname prob_lower_site_ae_vs_study_ae
#' @export
#' @importFrom purrr safely
prob_lower_site_ae_vs_study_ae <- function(site_ae, study_ae, r = 1000, parallel = F) {

  # if there is only one site
  if (is_null(study_ae)) {
    prob_lower <- 1
    return(prob_lower)
  }

  mean_ae_site <- mean(site_ae, na.rm = T)
  mean_ae_study <- mean(study_ae, na.rm = T)

  # we are not interested in cases where site AE is greater study AE
  if (mean_ae_site > mean_ae_study) {
    prob_lower <- 1
    return(prob_lower)
  }

  # set-up multiprocessing
  if (parallel) {
    requireNamespace("furrr")
    suppressWarnings(future::plan(multiprocess))
    .f_map_int <- furrr::future_map_int
  } else {
    .f_map_int <- purrr::map_int
  }

  pool <- c(site_ae, study_ae)
  n_pat <- length(site_ae)

  sim <- function(seed) {
    set.seed(seed)
    me <- mean(sample(pool, n_pat, replace = T))
    # '<=' includes all cases where mean_ae_site == 0 and me also == 0
    return(as.integer(ifelse(me <= mean_ae_site, 1, 0)))
  }

  df_sim <- tibble(seed = seq.int(1, r, 1)) %>%
    mutate(prob_lower = .f_map_int(.data$seed, .f = sim)) %>%
    summarise(prob_lower = sum(.data$prob_lower) / r)

  return(df_sim$prob_lower)
}


#' @title calculate prob_lower and poisson.test pvalue for study sites
#' @description collects the number of AEs of all eligible patients from that
#'   meet med75 criteria of site. Then uses calculates poisson.test pvalue and
#'   probability of having a lower mean value using simulation.
#' @param df_site dataframe
#' @param df_visit dataframe
#' @param r integer, denotes number of simulations, default = 1000
#' @param poisson_test logical, calculates poisson.test pvalue
#' @param prob_lower logical, calculates probability for getting a lower value
#' @return datafram with columns study_roche, site_number, visit_med75, pval, prob_low
#' @details " "
#' @examples
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.4, ur_rate = 0.2)
#' df_visit$study_roche <- "A"
#' df_site <- site_aggr(df_visit)
#' df_sim_sites <- sim_sites(df_site, df_visit, r = 100)
#' @rdname sim_sites
#' @export
#' @import dplyr
#' @import purrr
#' @import tidyr
sim_sites <- function(df_site,
                      df_visit,
                      r = 1000,
                      poisson_test = TRUE,
                      prob_lower = TRUE) {

  df_pat_pool <- pat_pool(df_visit, df_site)

  df_sim_prep <- df_visit %>%
    left_join(select(df_site,
                     .data$study_roche,
                     .data$site_number,
                     .data$visit_med75),
      by = c("study_roche", "site_number")
    ) %>%
    filter(.data$visit == .data$visit_med75) %>%
    group_by(.data$study_roche,
             .data$site_number,
             .data$visit_med75) %>%
    summarise(patients = list(unique(.data$patnum)))

  df_sim_prep <- df_sim_prep %>%
    left_join(df_pat_pool, "study_roche") %>%
    mutate(
      pat_pool = map2(.data$pat_pool, .data$visit_med75, function(x, y) filter(x, .data$visit == y)),
      n_ae_site = map2(.data$pat_pool, .data$patients, function(x, y) filter(x, .data$patnum %in% y)),
      n_ae_study = map2(.data$pat_pool, .data$patients, function(x, y) filter(x, ! .data$patnum %in% y)),
      n_ae_site = map(.data$n_ae_site, "n_ae"),
      n_ae_study = map(.data$n_ae_study, "n_ae")
    ) %>%
    select(- .data$patients,
           - .data$pat_pool)

  df_sim <- df_sim_prep

  if (poisson_test) {
    df_sim <- df_sim %>%
      mutate(pval = pmap_dbl(list(.data$n_ae_site, .data$n_ae_study, .data$visit_med75),
                             poiss_test_site_ae_vs_study_ae))
  }

  if (prob_lower) {
    df_sim <- df_sim %>%
      mutate(prob_low = map2_dbl(.data$n_ae_site, .data$n_ae_study,
        prob_lower_site_ae_vs_study_ae,
        r = r
      ))
  }

  df_sim %>%
    mutate(mean_ae_site_med75 = map_dbl(n_ae_site, mean),
           mean_ae_study_med75 = map_dbl(n_ae_study, mean)) %>%
    select(- n_ae_site, - n_ae_study) %>%
    select(.data$study_roche,
           .data$site_number,
           .data$visit_med75,
           .data$mean_ae_site_med75,
           .data$mean_ae_study_med75,
           everything()) %>%
    ungroup() %>%
    return()
}

#' @title configure study patient pool by site parameters
#' @description for simulating a study we need to configure the study patient
#'   pool to match the configuration of the sites
#' @param df_visit dataframe
#' @param df_site dataframe as created by site_aggr()
#' @param min_n_pat_with_med75 minimum number of patients with visit_med_75 for
#'   simulation, Default: 1
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' df_visit1 <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'                                       frac_site_with_ur = 0.4, ur_rate = 0.6)
#'
#' df_visit1$study_roche <- "A"
#'
#' df_visit2 <- boot_sim_test_data_study(n_pat = 1000, n_sites = 3,
#'                                       frac_site_with_ur = 0.2, ur_rate = 0.1)
#'
#' df_visit2$study_roche <- "B"
#'
#' df_visit <- bind_rows(df_visit1, df_visit2)
#'
#' df_site <- site_aggr(df_visit)
#'
#' df_config <- get_pat_pool_config(df_visit, df_site)
#'
#' df_config
#' @rdname get_pat_pool_config
#' @export
get_pat_pool_config <- function(df_visit, df_site, min_n_pat_with_med75 = 1) {

  # site_config are the number of sites with their individual visit_med75 and n_pat_with_med75
  df_site_config <- select(df_site,
                           .data$study_roche,
                           .data$site_number,
                           .data$visit_med75,
                           .data$n_pat_with_med75) %>%
    filter(.data$n_pat_with_med75 >= min_n_pat_with_med75)

  # pat_pool gives the patient pool for study from which we sample
  df_site_config <- df_site_config %>%
    left_join(pat_pool(df_visit, df_site), by = "study_roche")

  # adjusting pat_pool to configuration can be done outside of simulation loop

  df_site_config <- df_site_config %>%
    mutate(
      pat_pool = map2(.data$pat_pool, .data$visit_med75, function(x, y) filter(x, visit == y)),
      n_pat_study = map2_dbl(.data$pat_pool, .data$n_pat_with_med75, function(x, y) nrow(x) - y)
    ) %>%
    select(.data$study_roche,
           .data$site_number,
           .data$visit_med75,
           .data$n_pat_with_med75,
           .data$n_pat_study,
           .data$pat_pool)

  return(ungroup(df_site_config))
}

#' @title simulate studies
#' @description simulate pvalues and prob_lower values for testing
#' @param df_site dataframe
#' @param df_visit dataframe
#' @param min_n_pat_with_med75 integer, min number of patients with med75 at
#'   site to simulate, Default: 1
#' @param keep_ae logical, keep ae numbers in output dataframe memory increase
#'   roughly 30 percent, Default: F
#' @param parallel logical, toggles parallel processing on and of, Default: F
#' @param r integer, denotes number of simulations, Default: 1000
#' @param r_prob_lower nteger, denotes number of simulations for prob_lower
#'   value calculation,, Default: 1000
#' @param poisson_test logical, calculates poisson.test pvalue, Default: T
#' @param prob_lower logical, calculates probability for getting a lower value,
#'   Default: F
#' @param studies vector with study names, Default: NULL
#' @param .progress logical, show progress bar
#' @return dataframe
#' @examples
#' df_visit1 <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'                                       frac_site_with_ur = 0.4, ur_rate = 0.6)
#'
#' df_visit1$study_roche <- "A"
#'
#' df_visit2 <- boot_sim_test_data_study(n_pat = 1000, n_sites = 3,
#'                                       frac_site_with_ur = 0.2, ur_rate = 0.1)
#'
#' df_visit2$study_roche <- "B"
#'
#' df_visit <- bind_rows(df_visit1, df_visit2)
#'
#' df_site <- site_aggr(df_visit)
#'
#' sim_studies(ungroup(df_visit), ungroup(df_site), r = 3, keep_ae = TRUE)
#' @details  adds column with simulated probabilities for exqual or lower
#'   mean_ae at visit_med75
#' @rdname sim_studies
#' @export
#' @importFrom feather read_feather write_feather
#' @import dplyr
#' @import purrr
#' @import tidyr
#' @import furrr
#' @import future
#' @importFrom stringr str_count str_pad
#' @importFrom rlang :=
sim_studies <- function(df_visit,
                        df_site,
                        r = 100,
                        poisson_test = TRUE,
                        prob_lower = TRUE,
                        r_prob_lower = 1000,
                        parallel = FALSE,
                        keep_ae = FALSE,
                        min_n_pat_with_med75 = 1,
                        studies = NULL,
                        .progress = TRUE
                        ) {

  df_config <- get_pat_pool_config(df_visit = df_visit,
                                   df_site = df_site,
                                   min_n_pat_with_med75 = min_n_pat_with_med75)

  # filter studies --------------------------------------------
  if (!is_null(studies)) {
    if (!all(studies %in% unique(df_visit$study_roche))) {
      stop("not all passed studies can be found in input data")
    }

    df_config <- df_config %>%
      filter(.data$study_roche %in% studies)

  }

  # set-up multiprocessing -------------------------------------
  if (parallel) {
    requireNamespace("furrr")
    suppressWarnings(future::plan(multiprocess))
    .f_map <- function(...) {
      furrr::future_map(..., .progress = .progress)
    }
  } else {
    .f_map <- purrr::map
  }

  # sim function will be called r times -----------------------
  sim <- function(r) {
    set.seed(r)
    df_config <- df_config %>%
      mutate(
        n_ae_site = map2(.data$pat_pool, .data$n_pat_with_med75,
                         function(x, y) sample_n(x, y, replace = TRUE)),
        n_ae_site = map(.data$n_ae_site, "n_ae"),
        n_ae_study = map2(.data$pat_pool, .data$n_pat_study,
                          function(x, y) sample_n(x, y, replace = TRUE)),
        n_ae_study = map(.data$n_ae_study, "n_ae")
      ) %>%
      select(- .data$pat_pool)

    if (poisson_test) {
      df_config <- df_config %>%
        mutate(pval = pmap_dbl(list(.data$n_ae_site,
                               .data$n_ae_study,
                               .data$visit_med75),
                               poiss_test_site_ae_vs_study_ae))
    }

    if (prob_lower) {
      df_config <- df_config %>%
        mutate(prob_low = map2_dbl(.data$n_ae_site, .data$n_ae_study,
                                   prob_lower_site_ae_vs_study_ae,
                                   r = r_prob_lower))
    }

    if (!keep_ae) {
      df_config <- df_config %>%
        select(- .data$n_ae_site, - .data$n_ae_study)
    } else {
      df_config <- df_config %>%
        mutate_at(vars(n_ae_site, n_ae_study), ~ map_chr(., paste, collapse = ","))
    }

    return(ungroup(df_config))
  }

  df_sim <- tibble(r = seq.int(1, r, 1)) %>%
    mutate(n_ae_set = .f_map(.data$r, sim)) %>%
    unnest(.data$n_ae_set)

  return(ungroup(df_sim))
}



#' @title aggreagate from visit to site level
#' @description calculates visit_med75, n_pat_with_med75 and mean_ae_site_med75
#' @param df_visit dataframe
#' @param col_study_id_str column name for study id will be renamed to default
#'   in output, Default: study_roche
#' @param col_site_id_str column name for site id will be renamed to default in
#'   output, Default: site_number
#' @param col_patient_id_str column name for patient id will be renamed to
#'   default in output, Default: patnum
#' @param col_n_ae_str column name for number of ae will be renamed to default
#'   in output, Default: n_ae
#' @param col_visit_str column name for consecutive visit number will be renamed
#'   to default in output, Default: visit
#' @return dataframe
#' @details ' '
#' @examples
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.4, ur_rate = 0.6)
#' df_visit$study_roche <- "A"
#' df_site <- site_aggr(df_visit)
#' df_site
#' @rdname site_aggr
#' @export
site_aggr <- function(df_visit,
                      col_study_id_str = "study_roche",
                      col_site_id_str = "site_number",
                      col_patient_id_str = "patnum",
                      col_n_ae_str = "n_ae",
                      col_visit_str = "visit") {

  # rename columns
  df_visit <- df_visit %>%
    rename(study_roche = !! as.name(col_study_id_str),
           site_number = !! as.name(col_site_id_str),
           patnum = !! as.name(col_patient_id_str),
           visit = !! as.name(col_visit_str))

  # Aggregate on site level ------------------------------------------

  df_visit <- df_visit %>%
    group_by(.data$study_roche, .data$site_number, .data$patnum) %>%
    mutate(max_visit_per_pat = max(.data$visit))

  df_pat <- df_visit %>%
    select(.data$study_roche,
           .data$site_number,
           .data$patnum,
           .data$max_visit_per_pat) %>%
    distinct()

  df_site <- df_pat %>%
    group_by(.data$study_roche, .data$site_number) %>%
    mutate(
      n_patients = n_distinct(.data$patnum)
      # , visit_min = min(max_visit_per_pat)
      # , visit_median = median(max_visit_per_pat)
      # , visit_mean = mean(max_visit_per_pat)
      # , visit_max = max(max_visit_per_pat)
      , visit_med75 = ceiling(median(.data$max_visit_per_pat) * 0.75),
      n_pat_with_med75 = ifelse(.data$max_visit_per_pat >= .data$visit_med75, 1, 0),
      n_pat_with_med75 = sum(.data$n_pat_with_med75)
      # , freq_pat_with_med75 = n_pat_with_med75 / n_patients
    ) %>%
    select(- .data$patnum,
           - .data$max_visit_per_pat) %>%
    distinct()

  # Calculate mean cumulative AE at med75 per Site ------------------

  df_mean_ae_dev <- df_visit %>%
    left_join(df_site, by = c("study_roche", "site_number")) %>%
    filter(.data$visit <= .data$visit_med75, .data$max_visit_per_pat >= .data$visit_med75) %>%
    group_by(.data$study_roche, .data$site_number, .data$visit_med75, .data$visit) %>%
    summarise(mean_ae_site = mean(.data$n_ae)) %>%
    ungroup()

  df_mean_ae_med75 <- df_mean_ae_dev %>%
    filter(.data$visit == .data$visit_med75) %>%
    rename(mean_ae_site_med75 = .data$mean_ae_site) %>%
    select(.data$study_roche,
           .data$site_number,
           .data$mean_ae_site_med75)

  # Add mean cumulative AE to site aggreagate ----------------------

  df_site <- df_site %>%
    left_join(df_mean_ae_med75, by = c("study_roche", "site_number"))

  return(ungroup(df_site))
}


#' @title ttest for vector with site AEs vs vector with study AEs
#' @description sets pvalue=1 if mean AE site is greater than mean AE study or poisson.test gives error
#' @param site_ae vector with AE numbers
#' @param study_ae vector with AE numbers
#' @return pval
#' @details " "
#' @examples
#' ttest_site_ae_vs_study_ae(site_ae = c(5, 3, 3, 2, 1, 6), study_ae = c(9, 8, 7, 9, 6, 7, 8))
#' @seealso
#'  \code{\link[purrr]{safely}}
#' @rdname ttest_site_ae_vs_study_ae
#' @export
#' @importFrom purrr safely
#' @importFrom stats median runif t.test

ttest_site_ae_vs_study_ae <- function(site_ae, study_ae) {

  # if there is only one site
  if (is_null(study_ae)) {
    pval <- 1
    return(pval)
  }

  mean_ae_site <- mean(site_ae, na.rm = T)
  mean_ae_study <- mean(study_ae, na.rm = T)

  # we are not interested in cases where site AE is greater study AE
  if (mean_ae_site > mean_ae_study) {
    pval <- 1
    return(pval)
  }

  safely_ttest <- purrr::safely(t.test)

  ttest <- safely_ttest(site_ae, study_ae)

  pval <- ttest$result$p.value

  # this controls for cases where there are too few patients
  # to do a ttest
  if (is_null(pval)) {
    pval <- 1
  }

  return(pval)
}

#' @title poisson test for vector with site AEs vs vector with study AEs
#' @description sets pvalue=1 if mean AE site is greater than mean AE study or ttest gives error
#' @param site_ae vector with AE numbers
#' @param study_ae vector with AE numbers
#' @param visit_med75 integer
#' @return pval
#' @details " "
#' @examples
#' poiss_test_site_ae_vs_study_ae(
#'    site_ae = c(5, 3, 3, 2, 1, 6),
#'    study_ae = c(9, 8, 7, 9, 6, 7, 8),
#'    visit_med75 = 10
#')
#'
#' poiss_test_site_ae_vs_study_ae(
#'    site_ae = c(11, 9, 8, 6, 3),
#'    study_ae = c(9, 8, 7, 9, 6, 7, 8),
#'    visit_med75 = 10
#')
#' @seealso
#'  \code{\link[purrr]{safely}}
#' @rdname poiss_test_site_ae_vs_study_ae
#' @export
#' @importFrom purrr safely
#' @importFrom stats median runif poisson.test

poiss_test_site_ae_vs_study_ae <- function(site_ae,
                                             study_ae,
                                             visit_med75) {

  # if there is only one site
  if (is_null(study_ae)) {
    pval <- 1
    return(pval)
  }

  mean_ae_site <- mean(site_ae, na.rm = T)
  mean_ae_study <- mean(study_ae, na.rm = T)

  # we are not interested in cases where site AE is greater study AE
  if (mean_ae_site > mean_ae_study) {
    pval <- 1
    return(pval)
  }

  n_pat_site <- length(site_ae)
  n_pat_study <- length(study_ae)

  time_base_site <- n_pat_site * visit_med75
  time_base_study <- n_pat_study * visit_med75

  n_events_site <- sum(site_ae)
  n_events_study <- sum(study_ae)

  safely_poisson_test <- purrr::safely(poisson.test)

  poisson_test <- safely_poisson_test(c(n_events_site, n_events_study),
                                      c(time_base_site, time_base_study))

  pval <- poisson_test$result$p.value

  # this controls for cases when poisson.test fails for some reason
  if (is_null(pval)) {
    pval <- 1
  }

  return(pval)
}


#' @title simulate study test data
#' @description evenly distributes a number of given patients across a number of
#'   given sites. Then simulates ae development of each patient reducing the
#'   number of reported AEs for patients distributed to AE-underreporting sites.
#' @param n_pat integer, number of patients, Default: 1000
#' @param n_sites integer, number of sites, Default: 20
#' @param frac_site_with_ur fraction of AE under-reporting sites, Default: 0
#' @param ur_rate AE underreporting rate, will lower mean ae per visit used to
#'   simulate patients at sites flagged as AE-underreporting., Default: 0
#' @param max_visit_mean mean of the maximum number of visits of each patient,
#'   Default: 20
#' @param max_visit_sd standard deviation of maximum number of visits of each
#'   patient, Default: 4
#' @param ae_per_visit_mean mean ae per visit per patient, Default: 0.5
#' @return tibble with columns site_number, patnum, is_ur, max_visit_mean,
#'   max_visit_sd, ae_per_visit_mean, visit, n_ae
#' @details maximum visit number will be sampled from normal distribution with
#'   characteristics derived from max_visit_mean and max_visit_sd, while the ae
#'   per visit will be sampled from a poisson distribution described by
#'   ae_per_visit_mean.
#' @examples
#' set.seed(1)
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5)
#' df_visit[which(df_visit$patnum == "P000001"),]
#' df_visit <- boot_sim_test_data_study(n_pat = 100, n_sites = 5,
#'     frac_site_with_ur = 0.2, ur_rate = 0.5)
#' df_visit[which(df_visit$patnum == "P000001"),]
#' @rdname boot_sim_test_data_study
#' @export
boot_sim_test_data_study <- function(n_pat = 1000,
                                     n_sites = 20,
                                     frac_site_with_ur = 0,
                                     ur_rate = 0,
                                     max_visit_mean = 20,
                                     max_visit_sd = 4,
                                     ae_per_visit_mean = 0.5
                                     ) {
  tibble(patnum = seq(1, n_pat)) %>%
    mutate(patnum = str_pad(patnum, width = 6, side = "left", pad = "0"),
           patnum = paste0("P", patnum),
           site_number = seq(1, n_pat),
           site_number = cut(.data$site_number, n_sites, labels = FALSE),
           is_ur = ifelse(.data$site_number <= (max(.data$site_number) * frac_site_with_ur), TRUE, FALSE),
           site_number = str_pad(.data$site_number, width = 4, side = "left", pad = "0"),
           site_number = paste0("S", .data$site_number),
           max_visit_mean = max_visit_mean,
           max_visit_sd = max_visit_sd,
           ae_per_visit_mean = ifelse(.data$is_ur, ae_per_visit_mean * (1 - ur_rate), ae_per_visit_mean),
           aes = pmap(list(vm = max_visit_mean,
                           vs = max_visit_sd,
                           am = ae_per_visit_mean),
                      function(vm, vs, am) boot_sim_test_data_patient(
                        .f_sample_max_visit = function() rnorm(1, mean = vm, sd = vs),
                        .f_sample_ae_per_visit = function(max_visit) rpois(max_visit, am))),
           aes = map(aes, ~ tibble(visit = seq(1, length(.)), n_ae = .))) %>%
    unnest(aes)

}

#' @title simulate patient ae reporting test data
#' @description " "
#' @param .f_sample_ae_per_visit function used to sample the aes for each visit,
#'   Default: function(x) rpois(x, 0.5)
#' @param .f_sample_max_visit function used to sample the maximum number of aes,
#'   Default: function() rnorm(1, mean = 20, sd = 4)
#' @return vector containing cumulative aes
#' @details ""
#' @examples
#' replicate(5, boot_sim_test_data_patient())
#' replicate(5, boot_sim_test_data_patient(
#'     .f_sample_ae_per_visit = function(x) rpois(x, 1.2))
#'   )
#' replicate(5, boot_sim_test_data_patient(
#'     .f_sample_max_visit = function() rnorm(1, mean = 5, sd = 5))
#'   )
#' @importFrom stats ecdf rnorm rpois
#' @rdname boot_sim_test_data_patient
#' @export
boot_sim_test_data_patient <- function(.f_sample_max_visit = function() rnorm(1, mean = 20, sd = 4),
                                       .f_sample_ae_per_visit = function(max_visit) rpois(max_visit, 0.5)) {

  max_visit <- as.integer(.f_sample_max_visit())
  max_visit <- ifelse(max_visit < 1, 1, max_visit)
  aes <- .f_sample_ae_per_visit(max_visit)
  cum_aes <- cumsum(aes)

  return(cum_aes)
}
